{
  "$schema": "https://railway.com/railway.schema.json",
  "build": {
    "builder": "NIXPACKS",
    "watchPatterns": ["apps/backend/**"],
    "nixpacksPlan": {
      "providers": ["node"],
      "phases": {
        "install": {
          "dependsOn": ["setup"],
          "cmds": [
            "corepack enable",
            "corepack prepare yarn@stable --activate",
            "yarn install --immutable || yarn install"
          ]
        },
        "build": {
          "cmds": ["yarn build || echo no-build"]
        }
      }
    }
  },
  "deploy": {
    "startCommand": "sh -c \"cd apps/backend && corepack enable && corepack prepare yarn@stable --activate && yarn dlx @medusajs/cli@latest db:migrate && yarn medusa start -p ${PORT}\"",
    "restartPolicyType": "ON_FAILURE",
    "healthcheckPath": "/health"
  }
}
